# Generated by Django 5.0.1 on 2024-01-30 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_task_dude_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='dude_date',
            new_name='due_date',
        ),
    ]
