# Generated by Django 5.0.1 on 2024-01-30 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_rename_dude_date_task_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='task_photos/'),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(),
        ),
        migrations.DeleteModel(
            name='TaskPhoto',
        ),
    ]
